services:
  my-portfolio:
    image: thesharqx/portfolio:latest
    container_name: my-portfolio
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    ports:
      - 8080:8080

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my-portfolio