services:
  my-portfolio:
    image: thesharqx/portfolio:latest
    container_name: my-portfolio
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    ports:
      - 8080:8080

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - my-portfolio
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email shariquerahman24@gmail.com -d sharique.tech --agree-tos