version: "3.6"

services:
  website:
    restart: unless-stopped
    build: .
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - website