name: CI/CD Pipeline

on:
  push:
    branches: 
    - main

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build default.conf
        run: echo "${{ secrets.DEFAULT_CONF }}" | base64 --decode > /home/runner/work/portfolio/portfolio/default.conf
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: /home/runner/work/portfolio/portfolio
          tags: thesharqx/portfolio

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/portfolio
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -af